#!/usr/bin/env python3
"""Regenerate llms-full.txt: one offline snapshot of the core documentation.

Run from the repository root:

    python scripts/generate_llms_full.py

The manifest below is deliberately explicit rather than a glob. llms-full.txt is
documentation context for a model, not an archive: the terminal client's backlog,
design records and reports are useful to contributors but would bury the pages
that answer "what is this and how do I use it". Add a page here when it becomes
part of the core set.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "llms-full.txt"

DOCUMENTS = [
    "README.md",
    "docs/getting-started.md",
    "docs/architecture.md",
    "docs/api.md",
    "docs/workflows.md",
    "docs/ui_events.md",
    "docs/faq.md",
    "docs/troubleshooting.md",
    "docs/README.md",
    "docs/web.md",
    "docs/deployment-web.md",
    "docs/deployment-iphone.md",
    "tui/README.md",
    "tui/docs/getting-started.md",
    "tui/docs/api.md",
    "tui/docs/architecture.md",
    "tui/docs/troubleshooting.md",
    "tui/docs/faq.md",
    "web/README.md",
    "CHANGELOG.md",
    "CONTRIBUTING.md",
    "SECURITY.md",
    "ACKNOWLEDGEMENTS.md",
]

HEADER = """# AbstractCode — full documentation snapshot

Generated by scripts/generate_llms_full.py. This is the documentation only; it
contains no source code. See llms.txt for the linked index, and the repository
itself for the code and tests that are the source of truth.

"""


def main() -> int:
    missing = [name for name in DOCUMENTS if not (ROOT / name).is_file()]
    if missing:
        # Fail loudly: a silently skipped page is how these files go stale.
        print("missing documents:", ", ".join(missing), file=sys.stderr)
        return 1

    parts = [HEADER]
    for name in DOCUMENTS:
        parts.append(f"\n\n{'=' * 78}\n# FILE: {name}\n{'=' * 78}\n\n")
        parts.append((ROOT / name).read_text(encoding="utf-8").rstrip() + "\n")

    OUTPUT.write_text("".join(parts), encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)} from {len(DOCUMENTS)} documents "
          f"({OUTPUT.stat().st_size:,} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
